<?php
/**
 *
 *  * BSD 3-Clause License
 *  *
 *  * Copyright (c) 2018, Affirm
 *  * All rights reserved.
 *  *
 *  * Redistribution and use in source and binary forms, with or without
 *  * modification, are permitted provided that the following conditions are met:
 *  *
 *  *  Redistributions of source code must retain the above copyright notice, this
 *  *   list of conditions and the following disclaimer.
 *  *
 *  *  Redistributions in binary form must reproduce the above copyright notice,
 *  *   this list of conditions and the following disclaimer in the documentation
 *  *   and/or other materials provided with the distribution.
 *  *
 *  *  Neither the name of the copyright holder nor the names of its
 *  *   contributors may be used to endorse or promote products derived from
 *  *   this software without specific prior written permission.
 *  *
 *  * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 *  * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 *  * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 *  * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 *  * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 *  * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 *  * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 *  * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 *  * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 *  * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 */
?>
<?php
$mfpValue = $block->getMFPValue();
$productId = $block->getProductId();
$learnMore = $block->getLearnMoreValue();
?>


<span style="float: left; width: 100%; margin-bottom: 15px" data-mage-init='{"Astound_Affirm/js/aslowasPDP": <?php echo $block->getWidgetData(); ?>}'>
    <?php echo '<div id="als_pdp" data-amount="0" class="affirm-as-low-as" data-page-type="product" ' . (!empty($mfpValue) ? 'data-promo-id="' . $mfpValue . '"' : '') . ' ' . $block->getDataAffirmColor() . ' data-learnmore-show="'.$learnMore.'"></div>'; ?>
</span>

<script type="text/javascript">
    require(['jquery', 'affirmWidget'],function($){

        $(document).ready(function(){
            if (typeof affirm != "undefined") {
                affirm.ui.refresh();
            }
            $(".change-container-classname").on('change click', function () {
                if ($('#product-price-' +<?php echo $productId; ?>)) {
                    var refreshable = document.getElementById('als_pdp');
                    var amount = $('#product-price-' +<?php echo $productId; ?>).html();
                    var finalAmount = Number(amount.replace(/[^0-9\.-]+/g, "")) * 100;
                    refreshable.setAttribute('data-amount', finalAmount);
                    console.log('refreshALA', refreshable);
                    affirm.ui.refresh();
                }
            });

        });

    });

</script>
