<?php
/**
 * Astound
 * NOTICE OF LICENSE
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to codemaster@astoundcommerce.com so we can send you a copy immediately.
 *
 * @category  Affirm
 * @package   Astound_Affirm
 * @copyright Copyright (c) 2016 Astound, Inc. (http://www.astoundcommerce.com)
 * @license   http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php
$mfpValue = $block->getMFPValue();
$productId = $block->getProductId();
$learnMore = $block->getLearnMoreValue();
?>


<span style="float: left; width: 100%; margin-bottom: 15px" data-mage-init='{"Astound_Affirm/js/aslowasPDP": <?php echo $block->getWidgetData(); ?>}'>
    <?php echo '<div id="als_pdp" data-amount="0" class="affirm-as-low-as" ' . (!empty($mfpValue) ? 'data-promo-id="' . $mfpValue . '"' : '') . ' ' . $block->getDataAffirmColor() . ' data-learnmore-show="'.$learnMore.'"></div>'; ?>
</span>

<script type="text/javascript">
    require(['jquery', 'affirmWidget'],function($){

        $(document).ready(function(){
            if (typeof affirm != "undefined") {
                affirm.ui.refresh();
            }
            $(".change-container-classname").on('change click', function () {
                if ($('#product-price-' +<?php echo $productId; ?>)) {
                    var refreshable = document.getElementById('als_pdp');
                    var amount = $('#product-price-' +<?php echo $productId; ?>).html();
                    var finalAmount = Number(amount.replace(/[^0-9\.-]+/g, "")) * 100;
                    refreshable.setAttribute('data-amount', finalAmount);
                    console.log('refreshALA', refreshable);
                    affirm.ui.refresh();
                }
            });

        });

    });

</script>
