<?php
/**
 *
 *  * BSD 3-Clause License
 *  *
 *  * Copyright (c) 2018, Affirm
 *  * All rights reserved.
 *  *
 *  * Redistribution and use in source and binary forms, with or without
 *  * modification, are permitted provided that the following conditions are met:
 *  *
 *  *  Redistributions of source code must retain the above copyright notice, this
 *  *   list of conditions and the following disclaimer.
 *  *
 *  *  Redistributions in binary form must reproduce the above copyright notice,
 *  *   this list of conditions and the following disclaimer in the documentation
 *  *   and/or other materials provided with the distribution.
 *  *
 *  *  Neither the name of the copyright holder nor the names of its
 *  *   contributors may be used to endorse or promote products derived from
 *  *   this software without specific prior written permission.
 *  *
 *  * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 *  * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 *  * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 *  * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 *  * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 *  * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 *  * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 *  * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 *  * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 *  * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 */
?>

<?php

$options = $block->getOptions();

$enableSearchTrack = $block->isSearchTrackPixelEnabled();
$enableProductListTrack = $block->isProductListTrackPixelEnabled();
$enableProductViewTrack = $block->isProductViewTrackPixelEnabled();
$enableAddCartTrack = $block->isAddCartTrackPixelEnabled();
$enableAddChkStartTrack = $block->isAddChkStartTrackPixelEnabled();

$action   = $this->getRequest()->getFullActionName();

?>
<!-- BEGIN AFFIRM ANALYTICS CODE -->
<script type="text/x-magento-init">
{"*": {
        "affirmPixel": <?php echo $options ?>
    }
}
</script>

<script>
    require(['jquery', 'jquery/ui', 'affirmPixel'],function($, affirmPixel){
        $(window).load(function () {
            if (typeof affirm != "undefined") {
                <?php

                // Search
                if (($action == 'catalogsearch_result_index' || $action == 'catalogsearch_advanced') && ($enableSearchTrack)) {
                    $queryString = $this->getQueryString();
                    if($queryString) {
                        $queryString = isset($queryString) ? urlencode($queryString) : '';
                        echo "affirm.analytics.trackProductsSearched(\"" . $queryString . "\");";
                    }
                }
                //Product List Or Category Page Or Search results viewed
                if (($action == 'catalog_category_view' || $action == 'catalogsearch_result_index') && $enableProductListTrack ) {
                    $productListData = $this->getCategoryData();
                    if($productListData) {
                        $categoryId = isset($productListData['categoryId']) ? $productListData['categoryId'] : '';
                        $categoryName = isset($productListData['categoryName']) ? $productListData['categoryName'] : '';
                        echo "affirm.analytics.trackProductListViewed(
                    {
                        \"listId\":\"" . $categoryId . "\", 
                        \"category\":\"" . $categoryName . "\"
                    }, [{}]);";
                    }
                }

                // Product detail view
                if ($action == 'catalog_product_view' && $enableProductViewTrack ) {
                    $productData = $this->getProductData();
                    if($productData) {
                        $name = isset($productData['name']) ? $productData['name'] : '';
                        $productId = isset($productData['productId']) ? $productData['productId'] : '';
                        $currency = isset($productData['currency']) ? $productData['currency'] : '';
                        $price = isset($productData['price']) ? $productData['price'] : '';
                        echo "affirm.analytics.trackProductViewed(
                            {
                                \"name\":\"" . $name . "\", 
                                \"productId\":\"" . $productId . "\",
                                \"currency\":\"" . $currency . "\",
                                \"price\":\"" . $price . "\"
                            });";
                        if($enableAddCartTrack){
                            ?>
                            //Add Pixel Event to the button's click handler
                            if (typeof jQuery != 'undefined') {
                                jQuery('#product-addtocart-button').click(function () {
                                    affirm.analytics.trackProductAdded({
                                        name: '<?php echo $name ?>',
                                        productId: '<?php echo $productId ?>',
                                        currency: '<?php echo $currency ?>',
                                        price: <?php echo $price ?>
                                    });
                                });
                            }
                            <?php
                        }
                    }
                }

                // Cart viewed
                if ($action == 'checkout_cart_index' && ($enableAddCartTrack)) {
                    //Cart viewed
                    $cartProductsData = $this->getCartData();
                    if($cartProductsData) {
                        echo "affirm.analytics.trackCartViewed([";
                        foreach ($cartProductsData as $cartProduct) {
                            $name = isset($cartProduct['name']) ? $cartProduct['name'] : '';
                            $productId = isset($cartProduct['productId']) ? $cartProduct['productId'] : '';
                            $currency = isset($cartProduct['currency']) ? $cartProduct['currency'] : '';
                            $price = isset($cartProduct['price']) ? $cartProduct['price'] : '';
                            $quantity = isset($cartProduct['quantity']) ? $cartProduct['quantity'] : '';
                            echo "{
                            \"name\":\"" . $name . "\", 
                            \"productId\":\"" . $productId . "\",
                            \"currency\":\"" . $currency . "\",
                            \"price\":\"" . $price . "\",
                            \"quantity\":\"" . $quantity . "\"
                            },";
                        }
                        echo "], {});";
                    }

                }

                if (($action == 'checkout_index_index' || $action == 'onepagecheckout_index_index' || $action == 'onestepcheckout_index_index' || $action == 'opc_index_index') && ($enableAddChkStartTrack)) {
                    $quoteData = $this->getQuoteData();
                    if($quoteData) {
                        $checkoutId = isset($quoteData['checkoutId']) ? $quoteData['checkoutId'] : '';
                        $orderId = isset($quoteData['orderId']) ? $quoteData['orderId'] : '';
                        $currency = isset($quoteData['currency']) ? $quoteData['currency'] : '';
                        $total = isset($quoteData['total']) ? $quoteData['total'] : '';
                        $paymentMethod = isset($quoteData['paymentMethod']) ? $quoteData['paymentMethod'] : '';
                        echo "affirm.analytics.trackCheckoutStarted({
                            \"checkoutId\":\"" . $checkoutId . "\", 
                            \"currency\":\"" . $currency . "\",
                            \"total\":\"" . $total . "\",
                        },[";
                        $quoteProductsData = $this->getQuoteProductsData();
                        if($quoteProductsData) {
                            foreach ($quoteProductsData as $cartProduct) {
                                $name = isset($cartProduct['name']) ? $cartProduct['name'] : '';
                                $productId = isset($cartProduct['productId']) ? $cartProduct['productId'] : '';
                                $currency = isset($cartProduct['currency']) ? $cartProduct['currency'] : '';
                                $price = isset($cartProduct['price']) ? $cartProduct['price'] : '';
                                $quantity = isset($cartProduct['quantity']) ? $cartProduct['quantity'] : '';
                                echo "{
                                    \"name\":\"" . $name . "\", 
                                    \"productId\":\"" . $productId . "\",
                                    \"currency\":\"" . $currency . "\",
                                    \"price\":\"" . $price . "\",
                                    \"quantity\":\"" . $quantity . "\"
                                    },";
                                }
                        }
                        echo "]);";
                    }                }

                ?>
            };
        });
    });
</script>
<!-- END AFFIRM ANALYTICS CODE -->
