<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var \Magento\Payment\Block\Info $block
 * @see \Magento\Payment\Block\Info
 */
$specificInfo = $block->getSpecificInformation();
$title = $block->escapeHtml($block->getMethod()->getTitle());
?>
<dl class="payment-method">
    <dt class="title"><a href="<?php echo $block->getAffirmMainUrl(); ?>" target="_blank"><?php /* @noEscape */ echo __('Affirm'); ?></a></dt>
    <?php if ($specificInfo):?>
        <dd class="content">
            <table class="data table">
                <caption class="table-caption"><?php /* @noEscape */ echo $title; ?></caption>
                <?php foreach ($specificInfo as $label => $value):?>
                    <tr>
                        <th scope="row"><?php echo $block->escapeHtml($label)?></th>
                        <td>
                            <?php /* @noEscape */ echo nl2br($block->escapeHtml(implode("\n", $block->getValueAsArray($value, true))));?>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </table>
        </dd>
    <?php endif;?>
</dl>
<?php echo $block->getChildHtml()?>
